### ISSUE TITLE
Relax Guzzle Constraint

### ISSUE THREAD

**Issue by brodkin** [constantcontact/php-sdk#109]
Requiring a singular dependency version in Composer is inflexible and should be avoided. As a semver-compliant library Guzzle will not make breaking API changes within a major version. The current dependency definition makes the SDK incompatible with other libraries that require newer versions of Guzzle. Use wildcards or carets to allow for a wider array of dependency versions.

**Comment by WoogieNoogie** [comment]
Thanks for the recommendation, Ryan. I'll get this change in.

**Comment by WoogieNoogie** [comment]
Merged #111 and released version 2.1.1
