### ISSUE TITLE
problem with php older version

### ISSUE THREAD

**Issue by omar-faruk-sust** [constantcontact/php-sdk#110]
In one of my existing project i m using PHP version 5.3 but the constantcontact/php-sdk requires 5.4+ but i need to integrate this constantcontact service in a subscribe form. when someone subscribe our site i want to add the email address into constantcontact contact list. Can anybody help me?

**Comment by shannon7wallace** [comment]
Hi Omar, we can't do anything about the php 5.4+ requirement, but maybe you could use this option for a signup form instead: techblog.constantcontact.com/api/release-updates/announcing-a-new-signup-form-post-url/. I hope that helps!

**Comment by omar-faruk-sust** [comment]
@shannon7wallace thanks for your reply. Can i submit my form to constantcontact by ajax call? because my form is also submitting in our cms. how can i do that?  

and my action url is somthing like that 

https://visitor2.constantcontact.com/api/signup?ca=c70f2c3f-2111-4aa8-9fbe-944933b97ce9%20&email=omar@yahoo.com&list=1956285098

is it correct? in my form i have added two hidden filed ca and list.

**Comment by shannon7wallace** [comment]
Hi Omar, That looks correct and you should be able to use ajax for this. You'll specify POST as the method.

**Comment by omar-faruk-sust** [comment]
Yah I am making ajax via post this is fine. But can I do this same this via
curl?

**Comment by shannon7wallace** [comment]
Hi Omar, Yes, either curl or ajax will work.

**Comment by omar-faruk-sust** [comment]
Thanks let me try, if I face any problem I will knock u

**Comment by WoogieNoogie** [comment]
For something smaller like only contact sign up, that's definitely the way to go, I just wanted to note really quick that our version 1 SDK is compatible with 5.3, and can either be downloaded via composer or from a link in the current version's Readme.

**Comment by omar-faruk-sust** [comment]
hello, now i am trying to use CURL,

here is my written function. but it's not getting called.

function cc_insert_contact($email, $api_key =
'6bs989f94m6c3u9r7e7x9zqv',$access_token =
'3f6c24ed-2f80-4ee9-8703-2e84f2a9a746'){
        $caVal = '52b288b9-2aa1-4ff8-9ca8-3fe89eeba53f';
        $listVal = '1154077214';

        $service_url = '
https://visitor2.constantcontact.com/api/signup?ca='.$caVal.'&email='.$email.'&list='.$listVal
;

        $errors = array();
        $curl = curl_init($service_url);

        $header = array();
        $header[] = 'Authorization: Bearer '.$access_token;

        curl_setopt($curl, CURLOPT_HTTPHEADER,$header);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

        $curl_response = curl_exec($curl);
        if ($curl_response === false) {
            $info = curl_getinfo($curl);
            curl_close($curl);
            $errors[] = 'Error: '. var_export($info);
            die('error occured during curl exec. Additioanl info: ' .
var_export($info));
        }
        curl_close($curl);
        $decoded = json_decode($curl_response);

        if (isset($decoded->response->status) && $decoded->response->status
== 'ERROR') {
            die('error occured: ' . $decoded->response->errormessage);
        }

        if(! empty($errors)){
            return false;
        }else{
            return $decoded;
        }
    }

i am calling this method from another method.

**Comment by omar-faruk-sust** [comment]
hello @shannon7wallace , now i am trying to use CURL,
here is my written function. but it's not adding to the list.
```php
$this->cc_insert_contact($email="omar@yahoo.com");
function cc_insert_contact($email, $api_key =
'6bs989f94m6c3u9r7e7x9zqv',$access_token =
'3f6c24ed-2f80-4ee9-8703-2e84f2a9a746'){
        $caVal = '52b288b9-2aa1-4ff8-9ca8-3fe89eeba53f';
        $listVal = '1154077214';

        $service_url = '
https://visitor2.constantcontact.com/api/signup?ca='.$caVal.'&email='.$email.'&list='.$listVal
;
        $errors = array();
        $curl = curl_init($service_url);

        $header = array();
        $header[] = 'Authorization: Bearer '.$access_token;

        curl_setopt($curl, CURLOPT_HTTPHEADER,$header);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

        $curl_response = curl_exec($curl);
        if ($curl_response === false) {
            $info = curl_getinfo($curl);
            curl_close($curl);
            $errors[] = 'Error: '. var_export($info);
            die('error occured during curl exec. Additioanl info: ' .
var_export($info));
        }
        curl_close($curl);
        $decoded = json_decode($curl_response);

        if (isset($decoded->response->status) && $decoded->response->status
== 'ERROR') {
            die('error occured: ' . $decoded->response->errormessage);
        }

        if(! empty($errors)){
            return false;
        }else{
            return $decoded;
        }
    }
```
i am calling this method from another method. what is the worng? is this url format is correct?

**Comment by omar-faruk-sust** [comment]
@shannon7wallace i am trying to use CURL. the CURL is working fine in local with the constant contact but in the live it's not working with with constantcontact. is there any Idea about it?

**Comment by shannon7wallace** [comment]
Hi Omar, Of course in this case there has to be a difference between your test and production (live) environments. I'd check to see if any firewalls on the network might be causing an issue, and whitelist api.constantcontact.com on any security programs. Also check to make sure that your production environment has a valid security certificate and uses TLS 1.1 or above. TLS 1.0 with a non-RC4 cipher will also work.

**Comment by omar-faruk-sust** [comment]
thanks now it's working @shannon7wallace
