### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by camspanos** [constantcontact/php-sdk#115]
Fatal Error Error: Class 'GuzzleHttp\Client' not found in [/Library/WebServer/Documents/crm/vendor/constantcontact/constantcontact/src/Ctct/Services/BaseService.php, line 51]

What do I need to do to have it recognize the class?

I ran composer install and update
I am using cake as my framework

**Comment by camspanos** [comment]
I just figured it out the BaseService.php needed to require the vendor/autoload.php file I have it all working now.

**Comment by WoogieNoogie** [comment]
That's good to hear, sorry about not replying sooner - I was going to take a look at this today. Let us know if you need anything else!

**Comment by Arsenal21** [comment]
Where does the 'GuzzleHttp\Client' class come from?

Do we have to include the following library?
https://github.com/guzzle/guzzle

I can't see any "autoload.php" file inside that library.

**Comment by Arsenal21** [comment]
If something needs to be installed on the server before this API code example can be used then I have the following concern:

How can we expect an average user (not familiar with PHP or server software) to perform this kind of install on their server just so they can use an application which uses constant contact API?
