### ISSUE TITLE
action_by param invalid when calling addContact()?

### ISSUE THREAD

**Issue by JesseLeite** [constantcontact/php-sdk#122]
On develop branch, when calling `addContact()`, I'm getting action_by param errors.  Full details in [my form post here](https://community.constantcontact.com/t5/Developer-Support-ask-questions/Bad-request-when-trying-to-addContact/m-p/275962).

**Comment by JesseLeite** [comment]
Ohhh, I think you fixed this in commit d002af0.  Thank you :)

**Comment by WoogieNoogie** [comment]
:wink:
