### ISSUE TITLE
Unable to convert oAuth code with getAccessToken

### ISSUE THREAD

**Issue by zachshallbetter** [constantcontact/php-sdk#126]
Using v2.1.3 of constantcontact/constantcontact, when requesting the access token with `getAccessToken` using the code string returned from oAuth, I receive the following error which indicates the type is incorrect. I've tried converting the type with the same results.

> Argument 1 passed to Ctct\Exceptions\CtctException::setErrors() must be of the type array, object given, called in constantcontact/vendor/constantcontact/constantcontact/src/Ctct/Auth/CtctOAuth2.php on line 114

`oauth->getAccessToken($_GET['code']);`

**Comment by egaiter** [comment]
Hello,

After looking into this, I found a bug with how we parsed errors during OAuth, that resulted in this message. I've just submitted a pull request with a fix for this issue: #127 

After doing some extensive testing on the getAccessToken method, you should only be seeing this if one of the inputs is incorrect. Most likely the Client Secret or Redirect URI is not correct, but it's possible that the authorization code may have gotten malformed in your code. I would suggest double-checking the exact values that you're sending through for each of these to verify that they're all correct.
