### ISSUE TITLE
getBody() doesn't exist when trying to process error

### ISSUE THREAD

**Issue by troykelly** [constantcontact/php-sdk#128]
I'm getting this error:
Call to a member function getBody() on a non-object in ...BaseService.php (103)

When trying to: (from your example code)
$response = $cc->contactService->getContacts($this->config['ccontact']['apiToken'], array("email" => $email));

We are using App Engine - so this is their "curl lite". But still should not stop simple web requests from working.

**Comment by WoogieNoogie** [comment]
Sorry for the delay in getting back to you on this. What version are you currently using?

**Comment by troykelly** [comment]
We have moved to an alternative, constant contact was not suitable (didn't work & is not supported)
