### ISSUE TITLE
files to include in project

### ISSUE THREAD

**Issue by brody182** [constantcontact/php-sdk#130]
what files do i include in  my project? do I need to include /test/ directory? /composer/?

**Comment by WoogieNoogie** [comment]
If you're using composer, everything is brought in for you how you need it. If you're needing to use a standalone installation, check out the standalone zip file in this repo. You will need to include everything inside, then just require the Autoload.php file when you want to use the Constant Contact methods, and everything will be brought in automatically for you, dependencies and all.
