### ISSUE TITLE
Import Contact GuzzleHttp

### ISSUE THREAD

**Issue by alok12** [constantcontact/php-sdk#132]
Hello Sir,
I have tried to import member in constant contact but that is not working and given that error please help me to resolve it.
///URL REMOVED///
*_ERROR :- *_
`Fatal error: Uncaught exception 'InvalidArgumentException' with message 'A 'contents' key is required' in /home/imagetowebpage/public_html/demo/constant_contact/vendor/guzzlehttp/psr7/src/MultipartStream.php:83 Stack trace: #0 /home/imagetowebpage/public_html/demo/constant_contact/vendor/guzzlehttp/psr7/src/MultipartStream.php(70): GuzzleHttp\Psr7\MultipartStream->addElement(Object(GuzzleHttp\Psr7\AppendStream), Array) #1 /home/imagetowebpage/public_html/demo/constant_contact/vendor/guzzlehttp/psr7/src/MultipartStream.php(31): GuzzleHttp\Psr7\MultipartStream->createStream(Array) #2 /home/imagetowebpage/public_html/demo/constant_contact/vendor/guzzlehttp/guzzle/src/Client.php(302): GuzzleHttp\Psr7\MultipartStream->__construct(Array) #3 /home/imagetowebpage/public_html/demo/constant_contact/vendor/guzzlehttp/guzzle/src/Client.php(264): GuzzleHttp\Client->applyOptions(Object(GuzzleHttp\Psr7\Request), Array) #4 /home/imagetowebpage/public_html/demo/constant_contact/vendor/guzzlehttp/guzzle/src/Client.php(98): GuzzleHttp\Clien in /home/imagetowebpage/public_html/demo/constant_contact/vendor/guzzlehttp/psr7/src/MultipartStream.php on line 83`

**Comment by WoogieNoogie** [comment]
Sorry for the delay in getting back to you on this. If you still need assistance, we'll need a little more info, including what actions you're attempting when you receive this error. There may also be sensitive information, regarding contacts and account credentials, so I'm going to remove the URL you left here, close the topic, and ask that if you do still need help to email us at webservices@constantcontact.com

**Comment by goper-leo** [comment]
Ive encounter this. How to solve this sir? Anyone?
