### ISSUE TITLE
Can we use Guzzle 5.0.3

### ISSUE THREAD

**Issue by chiwek** [constantcontact/php-sdk#133]
I'm making a integration with ShopifyExtras/PHP-Shopify-API-Wrapper within the same laravel project and they use guzzle 5.0.3.

Since you guys require 5.1.0, is is possible to extend your sdk to work with guzzle 5.0.3 also?

**Comment by shannon7wallace** [comment]
Hi there,

We don't have the bandwidth to explore that right this moment, but if you switch over to the branch called "v1-master,"  it will be self-contained and guzzle version-independent.
