### ISSUE TITLE
Required files

### ISSUE THREAD

**Issue by roboron** [constantcontact/php-sdk#134]
The Add/Update example requires two files:

require_once '../src/Ctct/autoload.php';
require_once '../vendor/autoload.php';

I downloaded the 'php-sdk-master.zip' and extracted.
I see the first one in the 'src' folder but I don't see a 'vendor' folder at all.

**Comment by kflyingout** [comment]
yes, I have the same issue. The file ../vendor/autoload.php is not included in the .zip.

**Comment by WoogieNoogie** [comment]
The documentation assumes that you are installing via Composer. If you need to download the dependencies as well, you can use the vendor.zip file located in the standalone directory.
