### ISSUE TITLE
guzzle compatibility on php 7

### ISSUE THREAD

**Issue by RwwL** [constantcontact/php-sdk#157]
I set up a friend's site using this SDK on a PHP 5.x host, all was working fine, and then they migrated the site to a host running PHP 7.1.25. Since the migration, attempts to submit the form with the newsletter opt-in checked throw this error:

```Cannot use lexical variable $eventName as a parameter name in /home/[username]/public_html/vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 48```

Gonna go check the guzzle issues next, but thought I'd ask here first because it's included as a dependency of this SDK, which says it supports PHP 5.4+.

**Comment by jp555soul** [comment]
Just ran into the same error. 

Was there a solution?

**Comment by RwwL** [comment]
@jp555soul Yes but I can't recall what it was at the moment. I'll dig into my local copy when I get a chance later and let you know.

**Comment by jp555soul** [comment]
@RwwL Greatly appreciated brotha

**Comment by RwwL** [comment]
@jp555soul Ah, now I remember: the solution for me was to switch to an [alpha version of the SDK that they'd mentioned in their support forums](https://community.constantcontact.com/t5/Developer-Support-ask-questions/PHP-5-4-v-7-2/m-p/308035/highlight/true#M10962).

**Comment by jp555soul** [comment]
@RwwL Sweet! Thanks! I ended up updating Guzzle but will move this route to stay in sync.
