### ISSUE TITLE
Ctct\ConstantContact is getting too unwieldy

### ISSUE THREAD

**Issue by dsjellz** [constantcontact/php-sdk#34]
Ctct\ContantContact is too large, and is not scalable going forward. I have been working with GuzzlePHP (http://guzzlephp.org) in hopes to move to that framework. Unfortunately due to https://github.com/guzzle/guzzle/pull/398 I have been unable to complete this work.

At this point the GuzzlePHP bug needs to be resolved, or I will trim down the ConstantContact class into being a factory for the underlying services/clients.

**Comment by WoogieNoogie** [comment]
Fixed by #104 & #105 - v2.0.0
