### ISSUE TITLE
File retrieval endpoint

### ISSUE THREAD

**Issue by ewaltman** [constantcontact/php-sdk#86]
I can't seem to find any method for retrieving export files via the v2 /activities/<activity_id> endpoint (after receiving an activity id from addExportContactsActivity()). Am I missing something/Is there a best practice for retrieving these files through the SDK?

**Comment by WoogieNoogie** [comment]
I believe you're looking for the getActivity method on line 806 of ConstantContact.php.

**Comment by ewaltman** [comment]
Okay cool - Ya I realized that the getActivity method contains a file_name, but was wondering if there are any additions to that url (headers, params) required to actually file retrieval. The example in the docs only contain an api_key:
```
GET https://api.constantcontact.com/v2/activities/exportfiles/<activity_id>.<file_extension>?api_key=<api_key>
```
However, I was getting:
```
{
  error_key: "http.status.unauthorized",
  error_message: "No authentication is present."
}
```
Reading the text of the docs told me that an access_token should be passed as well, and now I see my file :grin: I'll close this out, but maybe that example should be update:
```
http://developer.constantcontact.com/docs/bulk_activities_api/bulk-activities-export-contacts.html
```

**Comment by WoogieNoogie** [comment]
Thanks for the feedback! We're always trying to find better ways to update our docs, especially when it comes to code examples. We'll try to clean this up for the future.
