### ISSUE TITLE
AddContacts Activity object does not allow for explicitly set column names

### ISSUE THREAD

**Issue by ewaltman** [constantcontact/php-sdk#87]
In the constructor of the AddContacts Activity class, the third parameter is an array of column names and it is optional. On line 34, there is an empty() check to determine whether this array was provided or not. If the array is not provided, the subsequent block will determine the column names automatically. 

However, when this parameter is provided, the resulting AddContacts instance has an empty column_names array and the contact is created with email alone.

This is confusing behavior, so the solutions are either to remove the optional columnNames parameter from AddContacts entirely, or to allow the user to pass in column names and then actually use them. I can make a PR if I have some time, and the first solution would obviously be faster to implement.

**Comment by WoogieNoogie** [comment]
We've previously seen this ( #37 ), and thought it to be fixed. Originally, the if statement checking for column names to be empty had no else, but we added one in and set the column names straight through. Would you be willing to share the code that's causing this to happen, and verify that you're running version 1.3 of the sdk?

**Comment by ewaltman** [comment]
I guess I hadn't pulled the latest version of the SDK because my copy of /Components/Activities/AddContacts.php lacks that *else*. I'll update my copy, close the issue, and everything should be fine. Thanks.
