### ISSUE TITLE
json.field.lists.value.invalid

### ISSUE THREAD

**Issue by sandeepts** [constantcontact/php-sdk#88]
$action = "Creating Contact";
         $contact = new Contact();
            $contact->addEmail('xxx@xxx.com'); //hgere
             $contact->addList('valuelistname');
 $returnContact = $cc->addContact(ACCESS_TOKEN, $contact, true);

I am getting error:
         [error_key] => json.field.lists.value.invalid
            [error_message] => The contact list xxxx does not exist.

when i debugged more and echo'ed request, i see 

,"lists":[{"id":"xxxx","name":null,"status":null,"contact_count":null}],

Any idea whats really causing?

**Comment by WoogieNoogie** [comment]
The parameter for $contact->addList() is either a complete ContactList object, or the ID of the list. It looks like you're trying to pass in the name, instead of passing in the ID.

**Comment by sandeepts** [comment]
actually I tried to id also, 
Array
(
    [0] => Array
        (
            [error_key] => json.type.invalid
            [error_message] => #/lists/0/id: Value is of a disallowed type. Allowed types are: String.
        )

)
Do you have any idea?

**Comment by WoogieNoogie** [comment]
If you are trying to set your List ID as an int or a long, it will not be accepted. The type of the variable has to be converted to a string. So, if your list ID is `$listId = 72`, it needs to be `$listId = "72"`.
