### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by nCrafts** [constantcontact/php-sdk#89]
Does the API have support for custom fields? I couldn't find an example us pulling the list of fields, and adding a contact with the custom fields.

**Comment by WoogieNoogie** [comment]
We do have support with custom fields, but it is limited as compared to what you can do in the UI. There is a thread on #29 that discusses how you can use custom fields through the API, and what limitations you will have to deal with. In this SDK, CustomField objects can be attached to Contact objects, but they do have to adhere to the restrictions described in the other thread.

**Comment by shannon7wallace** [comment]
Hi there, we don't have an example of pulling the list of fields, although you could simply print the contact object once you make a get Contact Details call. Here is how to add the custom fields to a contact. Note that the field names should be "CustomFieldn" since we don't have support for renamed custom fields.

$contact->custom_fields = array( 
array('label' => 'segment', 'name' => 'CustomField1', 'value' => 'Website Contact Form'), 
array('label' => 'other', 'name' => 'CustomField2', 'value' => 'Website Contact Form') 
); 

Thanks!
Shannon

**Comment by nCrafts** [comment]
I tried this. Your API wants both the label and name to be in the CustomFieldnn format. I have to use this to get it to work:

$contact->custom_fields = array( 
array('CustomField1' => 'segment', 'name' => 'CustomField1', 'value' => 'Website Contact Form'), 
array('CustomField2' => 'other', 'name' => 'CustomField2', 'value' => 'Website Contact Form') 
);

**Comment by nCrafts** [comment]
Any updates?

**Comment by shannon7wallace** [comment]
Hi nCrafts, 

Sorry, it looked to me like you had answered your own question. My apologies my code sample didn't work properly for your account (it had worked previously for my own).

I've updated my notes to reflect your changes. We also have it documented here (if you expand the custom field section) that the label and name need to be in the form CustomFieldnn.  http://developer.constantcontact.com/docs/contacts-api/contacts-resource.html

**Comment by nCrafts** [comment]
A little disappointing, but I guess it'll do. I hope you would consider allowing allowing a custom name, or label when we use the API, since it is allowed if we add the field using the Constant Contact dashboard.

**Comment by shannon7wallace** [comment]
Hi,

We have gotten feedback from our users on this limitation with custom fields, and are most definitely looking at adding this functionality in the future. I don't have any estimated timelines yet on when we'll be able to have this, but it is very high on our list of priorities.

**Comment by zheoreh** [comment]
Is it still not implemented?

**Comment by SeanDKendle** [comment]
3 years later, and we still can't send in Custom Fields with the names that were set in the UI?
