### ISSUE TITLE
Can't include constant contact class file

### ISSUE THREAD

**Issue by EvanHerman** [constantcontact/php-sdk#90]
Been working on this issue for the last couple of hours. When using this code that you've provided, using the appropriate path to the file on my server:

```php
require '/src/Ctct/autoload.php'
```

Seems to do nothing. As far as I can tell the class ConstantContact is not available for use.

Second, when I manually include the Constant Contact class file I just run into errors. It seems that all of the "use" statements cause some serious errors. I'm not entirely sure how to include any of the necessary files as it seems all of the php files contain at least one use statement in it.

If I manually include ConstantContact.php and then re-try to submit a request, I receive an error:
`Fatal error</b>:  Class 'ConstantContact' not found in <b>/nas/wp/www/cluster-1784/site/wp-content/themes/site/functions.php</b> on line <b>592</b><br />`.

Not sure what's going on, but it seems a little unnecessarily difficult just to include the main class file.

The instructions in the readme file of this repo don't seem to work, and my server meets all minimum requirements.

I'm running PHP v5.3.2 and CURL is enabled, not sure if that makes a difference.

Thanks,
Evan

**Comment by WoogieNoogie** [comment]
It's hard to know for sure without seeing your internal directory layout, but my first assumption from seeing you're working with Wordpress is that the require statement is not pointing to the correct location. #57 has a thread with two Wordpress developers that had a similar issue, and how they were able to solve it. Let us know if that's helpful.

**Comment by EvanHerman** [comment]
The path is definitly correct. I'm including two or three other files from the same directory. The file gets included fine, but I still see the error `Fatal error</b>: Class 'ConstantContact' not found in <b>/nas/wp/www/cluster-1784/site/wp-content/themes/site/functions.php</b> on line <b>592</b><br />.`

**Comment by shannon7wallace** [comment]
Hi Evan,

Since you're sure about the path, my best guess would be that there is something in your php configuration file (php.ini, probably) that's causing an issue. Reading up on this, a lot of developers have this issue when they try to use short php opening tags (<? ...  ?>) instead of <?php ... ?> , if they have short_open_tag=Off in the config file.

Best Regards,
Shannon Wallace
Partner API Support Engineer
