### ISSUE TITLE
create campagin throwing http.status.bad_request error

### ISSUE THREAD

**Issue by tahseen2k8** [constantcontact/php-sdk#94]
i am trying to use this sdk following the examples downloaded with sdk. insertion of contact example is working fine
but when i am trying to use create campaign example it is throwing the below error..
Array
(
    [0] => Array
        (
            [error_key] => http.status.bad_request
            [error_message] => Please enter an address
        )

)
every required thing i am posting but still this error showing cant figure out it any help will be higly appreciated..

**Comment by egaiter** [comment]
Hello,

When you're seeing this error, it indicates that the email campaign does not have a physical address associated with it. Normally if the account that you are using has an address associated with it, the email campaign will inherit that value and you are not required to set it.

However, in your case where the account does not have an address set, you are not able to create a campaign without an address. The simplest way to resolve this is to simply set up an address for your account. You can do that by logging in and navigating to My Account -> My Settings at the top-right.

If you continue to have issues after setting up a physical address, please let me know!

Elijah Gaiter
API Support Engineer
Constant Contact

**Comment by tahseen2k8** [comment]
Thanks 
Elijah Gaiter  it works for me.a very powerful email campaign sdk for php
thanks again
