### ISSUE TITLE
Expected params and documentation

### ISSUE THREAD

**Issue by godinaa** [constantcontact/php-sdk#95]
I've built out my integration with constant contact, and after digging through some things, I have a couple suggestions or points of confusion to bring up.

It's difficult to tell which objects are accepted by some factory methods or constructor params without looking at the code itself. Most arguments are just an array (which is nice for flexibility), but it's not documented what is expected in those arrays. For example, in `Contact::create()`, the email_addresses property is expected to be an array of props to pass to `EmailAddress::create()`. That's not obvious, since when you look at the documentation for the email_addresses property, it's expecting an array of EmailAddresses.

Also some classes don't have a factory method, leading to further digging through those classes to find what the constructor is expecting (AddContacts as an example).

I think all is well in the way it's designed but it just took a bit to dig through each class and find out how each property is used on factory methods and constructors.

I'm happy to add things to this. Do you accept pull requests?

**Comment by godinaa** [comment]
I just though about this a little more, and it does make sense that all factory methods would always call other factory methods, so it might just be me that wasn't used to this class design.

**Comment by WoogieNoogie** [comment]
We're always happy to accept suggestions and pull requests. The plans are to, likely fairly soon, update to version 2 which has some better documentation, and some moving around of how to call possibly confusing methods - so I would recommend keeping an eye out for when we release that, and focus on any improvements there, so they aren't immediately overwritten by our next merge.

**Comment by godinaa** [comment]
Cool, thanks for the reply. I'll look for version 2 and see how I can help in any way.
