### ISSUE TITLE
ArchiveURL, Archivestatus still in SDK Test Docs

### ISSUE THREAD

**Issue by csciuto** [constantcontact/php-sdk#97]
A developer brought up the issue in this community post:
https://community.constantcontact.com/t5/Developer-Support-ask-questions/ArchiveURL-missing-from-Campaign-details-in-API-v2/m-p/229439#M9145

They always return null, but it's raising questions with developers, causing confusion, hesitation. 

We have by design removed support for email campaign archive_url and archive_status in AppConnect, but the functions still exist in one of our test documentation

https://github.com/constantcontact/php-sdk/blob/cbfbedb6eb6e068d3d8c35ebb8e8c51ac7487bc5/test/Json/Campaigns/get_campaign.json

**Comment by WoogieNoogie** [comment]
Fixed by #98 , removed any references to these fields in our tests. There were no references in the objects.
